### ISSUE TITLE
Unable to connect to Hotspot in Android 5.0 and above

### ISSUE THREAD

**Issue by Harishy** [nickrussler/Android-Wifi-Hotspot-Manager-Class#11]
Hi Droid,

I tried it is working fine in below Android5.0 versions. But when i tried to run it in the Android 5.0 and above it is not switching the device from Wifi to Hotspot.

Thanks
Harish

**Comment by nickrussler** [comment]
Hi Harish,
i don't have a Android 5.0 device at hand so it's kind of hard to debug it, i would be glad to merge a pull request!

**Comment by Harishy** [comment]
If you find any solution, Please let me know.

**Comment by GT500R** [comment]
I found a solution to fix this issue. Please take a look at https://github.com/nickrussler/Android-Wifi-Hotspot-Manager-Class/pull/12.

**Comment by Harishy** [comment]
Thanks Nick. Working fine checked in couple of device with Version 5.0 and 5.0.2.
Thankyou .

**Comment by nickrussler** [comment]
Thanks go out to @GT500R :-)

**Comment by Harishy** [comment]
what is @GT500R..

**Comment by GT500R** [comment]
I'm now working on Android Marshmallow and set the targetSdkVersion to 23. Things get even trickier because of the new permissions. In addition WRITE_SETTINGS is also needed and you have to grant this permission in system settings on API 23+.
`<uses-permission android:name="android.permission.WRITE_SETTINGS" />`
**This can not be done like other permissions eg. camera, location because it is different from any other permission.** Have a look at https://developer.android.com/reference/android/Manifest.permission.html#WRITE_SETTINGS and http://stackoverflow.com/questions/32083410/cant-get-write-settings-permission/32083622#32083622

**Comment by Harishy** [comment]
Thanks for sharing information.Currently i don't have Android 6.0 OS
device.. will try to find the device and test. It seems you are yet to add
this in the repository.

Regards
Harish

**Comment by nickrussler** [comment]
http://stackoverflow.com/a/32083622
and
http://stackoverflow.com/a/35285034
seem to be good starting points.

**Comment by Harishy** [comment]
Hi Nick,

I have some doubts could you please help me on those.Those are related to
the Wifi And Hotspot related.
Is it right ti ask here or can you provide other mail id if you don't mine.

Thanks
Harish

**Comment by nickrussler** [comment]
You can find my email here: https://www.whitebyte.info/about
